#!/usr/bin/env bash
# dpw@plaza.localdomain
# 2023-10-18 19:11:24
#
#

INC='/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12'
INC='/home/dpw/.pyenv/versions/3.12.0/include/python3.12'

gcc -shared -pthread -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing -lm -I$INC -o hello.so hello.c
