#!/usr/bin/env bash
# dpw@Darryls-iMac.localdomain
# 2023-01-31 22:52:45
#

set -eu

printf "start the redis client\n"

[ -f ./env ] && source ./.env
[ -f ./db/.env ] && source ./db/.env

redis-cli -p $REDIS_PORT 

